# List the pdf's to build. foo.tex will produce foo.pdf
TARGETS = foo.pdf

# List the files included in the slides
DEPS = 

# Relative path to the LaTeX documentclass setup files
# Adapt as needed
RELPATH = $(shell git rev-parse --show-toplevel)/subject/

# You should not touch this either
include $(RELPATH)/Makefile.LaTeX
